---
title: "Mercari Price Suggestion"
author: "Aman Adhav, Qien Song"
output:
    pdf_document:default
    html_document:default
---


```{r}
library(lubridate)
library(ggplot2)
library(timeSeries)
library(dplyr)
library(tidyr)
library(stringr)
library(reshape2)
library(directlabels)
library(data.table)
library(mltools)
library(rpart)
library(partykit)
library(dummies)

```

Reading Data
```{r}
mercari_df <- read.delim(file="train.tsv", header=TRUE)
mercari_df$item_condition_id <- factor(mercari_df$item_condition_id)

```
Add broad category to help onehotencoding in the future
```{r}
mercari_df$general_cat <- factor(str_split_fixed(as.character(mercari_df$category_name), "/", 3)[,1])
mercari_df$secondary_cat <- factor(paste(mercari_df$general_cat, str_split_fixed(as.character(mercari_df$category_name), "/", 3)[,2], sep = '/'))
mercari_df$missing_description = ifelse(mercari_df$item_description == "No description yet", 1, 0)
mercari_df$missing_brand = ifelse(mercari_df$brand_name == "", 1, 0)


```

General Description
```{r}
str(mercari_df)
```
```{r}
summary(mercari_df)
```

Distribution of Item Condition
```{r}
boxplot(as.numeric(mercari_df$item_condition_id), horizontal=TRUE, main="Distribution of Item Condition")
```

Price distribution of goods less than $150
```{r}
hist(mercari_df[mercari_df$price < 150,]$price, freq=TRUE)
```


Number of Unique item in each row
```{r}
apply(mercari_df, 2, function(x) length(unique(x)))
```

Goods are 8 dollars more expensive if no free shipping is offered
```{r}
group_by_shipping = mercari_df %>% group_by(shipping) %>% summarise_at(vars(price),funs(mean(.,na.rm=TRUE)))
ggplot(group_by_shipping, aes(x = factor(shipping), y = price)) + geom_histogram(stat = 'identity')

```

```{r}
group_by_category = mercari_df %>% group_by(general_cat) %>% summarise_at(vars(price),funs(mean(.,na.rm=TRUE)))
group_by_category = arrange(group_by_category, desc(price))
ggplot(group_by_category, aes(x = general_cat, y = price)) + geom_histogram(stat = 'identity')
```

```{r}
group_by_category
```
Price depending on Condition
```{r}
group_by_condition = mercari_df %>% group_by(item_condition_id) %>% summarise_at(vars(price),funs(mean(.,na.rm=TRUE)))
ggplot(group_by_condition, aes(x = item_condition_id, y = price)) + geom_histogram(stat = 'identity')
```

```{r}
group_by_ship_cond = mercari_df %>% group_by(shipping, item_condition_id) %>% summarise_at(vars(price),funs(mean(.,na.rm=TRUE)))
ggplot(group_by_ship_cond, aes(x = item_condition_id, y = price)) + geom_bar(stat='identity', position ='dodge', aes(fill = factor(shipping)))
```

No null values

```{r}
sapply(mercari_df, function(x) sum(x==""))
```
Removes all null values
```{r}
series <- na.omit(mercari_df$item_condition_id)
table(series)
```
Item Description Analysis
```{r}
item_description_ana <- grep("No ", mercari_df$item_description, value=TRUE)
head(item_description_ana)
```

```{r}
null_df <- mercari_df[mercari_df$item_description == "No description yet",]
head(null_df)

boxplot(null_df$price, horizontal=TRUE, main="Distribution of Item Price for items without description")

summary(null_df$price)

```

```{r}
iqr <- 15 * 1.5

null_df_filtered <- null_df[null_df$price < iqr ,]

boxplot(null_df_filtered$price, horizontal=TRUE, main="Distribution of Item Price for items without description and without outliers")
```

```{r}
boxplot(mercari_df[mercari_df$price < iqr,]$price, horizontal = TRUE, freq=TRUE)

summary(mercari_df$price)

mercari_df$missing_description = ifelse(mercari_df$item_description == "No description yet", 1, 0)

```

```{r}


group_by_missing = mercari_df %>% group_by(missing_description, missing_brand, general_cat) %>% summarise_at(vars(price),funs(mean(.,na.rm=TRUE)))

group_by_missing_secondary = mercari_df %>% group_by(missing_description, missing_brand, secondary_cat) %>% summarise_at(vars(price),funs(mean(.,na.rm=TRUE)))

group_by_missing

```

```{r}
ggplot(group_by_missing,
       aes(x=general_cat, y=price)) +
  geom_bar(stat = "identity",position=position_dodge(), aes(fill = factor(missing_brand))) + coord_flip()

ggplot(group_by_missing,
       aes(x=general_cat, y=price)) +
  geom_bar(stat = "identity",position=position_dodge(), aes(fill = factor(missing_description))) + coord_flip()

ggplot(group_by_missing_secondary,
       aes(x=secondary_cat, y=price)) +
  geom_bar(stat = "identity",position=position_dodge(), aes(fill = factor(missing_brand))) + coord_flip()

```
```{r}
#Missing Description, Missing Brand 
group_by_missing
```

```{r}
group_by_missing_secondary
```

```{r}
head(mercari_df[mercari_df$general_cat == 'Beauty', ]
```

```{r}
```

```{r}
```

```{r}
n <- nrow(mercari_df)
set.seed(1111)
training_indices <- sample(1:n, size= round(0.9*n))
train <- mercari_df[training_indices,]
tree <- rpart(mercari_df$price ~ mercari_df$item_condition_id + mercari_df$shipping + mercari_df$missing_description + mercari_df$missing_brand, data = train, method='anova')
plot(as.party(tree), type="simple", gp=gpar(cex=0.8))
test <- mercari_df[-training_indices,]
```

```{r}
predictions <- predict(object = tree, newdata = test, type = "class")
head(predictions)
table(predictions)
```

```{r}
summary(tree)
```

```{r}
library(randomForest)
library(caret)
library(e1071)
```

```{r}
trControl <- trainControl(method = 'cv', number = 10,  search = 'grid')
n <- nrow(mercari_df)
set.seed(1111)
training_indices <- sample(1:n, size= round(0.01*n))
```

```{r}
model <- train(price ~ item_condition_id + general_cat + shipping + missing_description + missing_brand,
    data = mercari_df[training_indices,],
    method = "rf",
    metric = "RMSE",
    trControl = trControl)
```

```{r}
names(mercari_df)
```

```{r}
head(dummy_df)
```

```{r}
dummy_df <- cbind(mercari_df,dummy(mercari_df$secondary_cat, sep = '_', drop = FALSE))
dummy_df <- cbind(dummy_df,dummy(mercari_df$item_condition_id, sep = '_',  drop = FALSE))
dummy_df <- within(dummy_df, rm(name, category_name, brand_name, secondary_cat,general_cat, item_description, train_id,item_condition_id))
n <- nrow(dummy_df)
set.seed(1111)
training_indices <- sample(1:n, size= round(0.8*n))
```

```{r}
model <- glm('price ~ .', family = gaussian, dummy_df[training_indices,])
summary(model)
```

```{r}
```

```{r}
cbind(predict.lm(model, dummy_df[-training_indices,]),dummy_df[-training_indices,])
```

